#!/bin/bash

# Bash script to convert 'An Image File Name.jpg' to 'an_image_file_name.jpg' (snake case)

# Get all image file names in the folder
# Turn the filenames lowercase
# Replace spaces with _

# Commands:
# - `rename -n 's/ /_/g' *.{jpeg,jpg,png}` to replace all spaces with underscores
# - `rename -n 'y/A-Z/a-z/'` to lowercase everything
# - `|` will basically take all the filenames generated by the first rename command and pipe them as input to the next rename command

for file in ./*.{jpg,jpeg,png}
do
  mv "$file" "$(echo $file | awk '{print tolower($0)}' | sed 's/ /_/g')"
done

# NOTES:
# You can also do: rename 's/ /_/g' *.{jpeg,jpg,png} | rename 'y/A-Z/a-z/'
# But rename is not installed by default and you'll need sudo in order to install it